version: "3.1"

services:
 keycloak-db:
   image: postgres:17
   command:
     ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
   environment:
     POSTGRES_DB: keycloak
     POSTGRES_USER: keycloak
     POSTGRES_PASSWORD: keycloak
   ports:
     - "5432:5432"
   volumes:
     - keycloak-db:/var/lib/postgresql/data

 keycloak:
   image: quay.io/keycloak/keycloak:26.1.0
   environment:
     KC_DB: postgres
     KC_DB_URL_HOST: keycloak-db
     KC_DB_USERNAME: keycloak
     KC_DB_PASSWORD: keycloak
     KC_DB_URL_PORT: 5432
     KC_HOSTNAME: localhost
     KC_HOSTNAME_PORT: 8080
     KC_HOSTNAME_STRICT: false
     KC_PROXY: edge
     KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USERNAME}
     KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
   command: ["start-dev", "--import-realm"]
   volumes:
     - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
   ports:
     - "18080:8080"
   depends_on:
     - keycloak-db
   restart: unless-stopped

 backend:
   build:
    context: ./backend
    dockerfile: Dockerfile
   depends_on:
    - keycloak
   ports:
    - "9000:9000"
   environment:
    - GITLAB_TOKEN=${GITLAB_TOKEN}
    - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://localhost:18080/realms/bpmn-diff
    - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://keycloak:8080/realms/bpmn-diff/protocol/openid-connect/certs
    - FRONTEND_URL=http://localhost:3000
    - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG

 frontend:
   build:
    context: ./frontend
    dockerfile: Dockerfile
   depends_on:
    - backend
   environment:
    - KEYCLOAK_URL=http://localhost:18080/
    - KEYCLOAK_REALM=bpmn-diff
    - KEYCLOAK_CLIENT_ID=frontend-react
    - BACKEND_URL=http://localhost:9000/
   ports:
    - "3000:80"

volumes:
 keycloak-db: