apiVersion: v1
kind: Secret
metadata:
  name: frontend-user-secret
type: Opaque
stringData:
  FRONTEND_USER_USERNAME: {{ .Values.frontend.user.username }}
  FRONTEND_USER_LASTNAME: {{ .Values.frontend.user.lastName }}
  FRONTEND_USER_FIRSTNAME: {{ .Values.frontend.user.firstName }}
  FRONTEND_USER_PASSWORD: {{ .Values.frontend.user.password }}
  FRONTEND_USER_EMAIL: {{ .Values.frontend.user.email }}