postgresql:
  image: postgres:17
  database: keycloak
  user: keycloak
  password: keycloak

keycloak:
  image: quay.io/keycloak/keycloak:26.1.0
  admin:
    username: admin
    password: admin
  realm: bpmn

frontend:
  image: avcharpentier45/bpmn-diff-frontend:1.0
  clientId: frontend-react
  user:
    username: demo
    firstName: demo
    lastName: demo
    password: demo
    email: demo@gmail.com

backend:
  image: avcharpentier45/bpmn-diff-backend:1.0
  gitlab:
    token: glpat-XXX-XXX.XXX
    url: https://gitlab.com

# Liste des secrets utilis√©s pour pull les images (optionnel)
# Exemple :
# imagePullSecrets:
#   - name: my-registry-secret
imagePullSecrets: []

ingress:
  enabled: true
  openshift: false
  keycloak: keycloak.localhost
  frontend: bpmndiff.localhost
  backend: backend.localhost
