postgresql:
  image: postgres:17
  database: keycloak
  user: keycloak
  password: keycloak

keycloak:
  image: quay.io/keycloak/keycloak:26.1.0
  adminUser: admin
  adminPassword: admin
  hostname: http://keycloak:80

ingress:
  enabled: true
  keycloak: keycloak.localhost
  frontend: bpmndiff.localhost
  backend: backend.localhost

frontend:
  image: avcharpentier45/bpmn-diff-frontend:1.0
  clientId: frontend-react

backend:
  image: avcharpentier45/bpmn-diff-backend:1.0

gitlab:
  token: glpat-BWr1Lis6zEY-L7rdAaVZAG86MQp1OjNzbGtkCw.01.121ho3kvv
  url: https://gitlab.com

# Liste des secrets utilis√©s pour pull les images (optionnel)
# Exemple :
# imagePullSecrets:
#   - name: my-registry-secret
imagePullSecrets: []