postgresql:
  image: postgres:17
  database: keycloak
  user: keycloak
  password: keycloak

keycloak:
  image: quay.io/keycloak/keycloak:26.1.0
  adminUser: admin
  adminPassword: admin
  hostname: keycloak.localhost

ingress:
  enabled: true
  host: keycloak.localhost

frontend:
  image: my-frontend-image:latest
  hostname: bpmn-diff.localhost
